services:
  app:
    image: node:16
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      MONGODB_URI: "mongodb://db:27017/portfolio_test"
    networks:
      - app-network
    
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
